# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68dab98fbbf4b3c377bf5784c31271a8b91a1cb0deb146f5ae2ad02b6e879e2538cdcc52c998de16c9db3e26803b6fc0334c0020e4fcdc9fe64658d0b14fdc4d

test:
  secret_key_base: 3cfc431d628b428e5710a89962b40c1fd505ac63172516af3bb401f05c01b8b4003d44be7301d6cf3530542beac9859c9983bb4c9fda5bc981a046b46b4060c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
